export type LangType = 'EN' | 'JP' | 'CN' | 'ES';

export const DICTIONARY = {
    EN: {
        titles: {
            risk_score: "Market Regime Indicator",
            insights: "OmniMetric: Quantitative Macro Insights",
            risk_factors: "Institutional Data Grid",
            legal: "LEGAL NOTICE & DISCLAIMER",
            delayed: "1H Delay",
            partner_ad: "Institutional Partner Placement",
            market_regime: "MARKET REGIME",
            risk_preference: "RISK PREFERENCE",
            institutional_analysis: "Institutional AI Analysis",
            sponsored: "SPONSORED",
            current_strategy: "CURRENT STRATEGY",
            upcoming_events: "UPCOMING RISK EVENTS",
            gms_score: "GMS SCORE",
            breaking_news: "BREAKING NEWS",
            delayed_tick: "*15m DLY",
            methodology: "METHODOLOGY"
        },
        methodology: {
            title: "GMS QUANT METHODOLOGY",
            desc: "The GMS Score integrates market 'Fear', 'Credit Stress', and 'Momentum' into a proprietary 0-100 quantitative risk index.",
            zone_accumulate: "60-100: ACCUMULATE (Risk On)",
            zone_accumulate_desc: "Expansion phase. Inflows to Equities, Commodities, and High Yield bonds suggested.",
            zone_neutral: "40-60: NEUTRAL (Trendless)",
            zone_neutral_desc: "Volatility compression. Position adjustment phase.",
            zone_defensive: "0-40: DEFENSIVE (Risk Off)",
            zone_defensive_desc: "Cash/Treasury dominance. Watch for panic selling and credit contraction.",
            inputs: "Inputs: VIX, MOVE, HY OAS, NFCI, SPY Momentum",
            scale_labels: {
                panic: "Panic (0)",
                neutral: "Neutral (50)",
                greed: "Greed (100)"
            }
        },
        strategy: {
            accumulate: "ACCUMULATE",
            neutral: "NEUTRAL",
            defensive: "DEFENSIVE"
        },
        events: {
            cpi: "CPI INFLATION DATA",
            fomc: "FOMC RATE DECISION",
            nfp: "NON-FARM PAYROLLS",
            high: "HIGH IMPACT",
            critical: "CRITICAL",
            tue: "TUE",
            wed: "WED",
            fri: "FRI",
            est: "EST"
        },
        attribution: {
            src: "SRC: FRED/CBOE • UPD: LIVE"
        },
        terms: {
            VIX: {
                def: "Volatility Index. Measures expected market volatility.",
                benchmark: "Ref: <15 (Complacency), >20 (Caution), >30 (Panic)."
            },
            MOVE: {
                def: "Bond Market Volatility. The 'VIX' of Treasuries.",
                benchmark: "Ref: >120 indicates systemic stress in collateral markets."
            },
            NFCI: {
                def: "National Financial Conditions Index (Chicago Fed).",
                benchmark: "Ref: Positive = Tight (Bearish). Negative = Loose (Bullish)."
            },
            HY_SPREAD: {
                def: "High Yield Option-Adjusted Spread.",
                benchmark: "Ref: <3.5% (Healthy Risk Appetite), >5.0% (Credit Stress)."
            },
            COPPER_GOLD: {
                def: "Copper/Gold Ratio. Proxy for Global Growth vs Safety.",
                benchmark: "Ref: Rising trend signals economic expansion."
            },
            BREADTH: {
                def: "Market Breadth (RSP vs SPY Performance).",
                benchmark: "Ref: Positive spread indicates healthy broad participation."
            },
            SPY: {
                def: "SPDR S&P 500 ETF. Global Equity Risk proxy.",
                benchmark: "Ref: Uptrend = Risk On."
            },
            TNX: {
                def: "10-Year Treasury Yield.",
                benchmark: "Ref: >4.5% pressures equity valuations."
            },
            DXY: {
                def: "US Dollar Index.",
                benchmark: "Ref: >105 tightens global liquidity."
            },
            YIELD_SPREAD: {
                def: "10Y-2Y Yield Spread.",
                benchmark: "Ref: Inversion (<0) is a leading recession indicator."
            }
        },
        legal_text: {
            t1: "OmniMetric ('The Ultimate Asset Hub') provides quantitative macro insights for informational purposes only. The information presented herein is generated by OmniMetric Proprietary Algorithms and does not constitute investment advice. UNAUTHORIZED AUTOMATED SCRAPING, DATA MINING, OR USAGE FOR AI TRAINING IS STRICTLY PROHIBITED WITHOUT A COMMERCIAL LICENSE BY OMNIMETRIC. By accessing this site, you acknowledge and accept these terms.",
            t2: "Past performance is not indicative of future results. Market data provided 'as is'.",
            copyright: "Powered by OmniMetric Project 2026"
        },
        regime: {
            bull: "Risk Preference",
            neutral: "Neutral Regime",
            bear: "Risk Avoidance",
            legend: "BULL > 60 // BEAR < 40"
        },
        sections: {
            s1: "SECTION I: MARKET VOLATILITY & FEAR",
            s2: "SECTION II: STRUCTURAL CREDIT & FORECASTS",
            s3: "SECTION III: REFERENCE BENCHMARKS"
        },
        chart: {
            trend: "30-Day Terminal Trend",
            sync: "Awaiting Signal Sync...",
            insight: "Proprietary Insight",
            engine: "Institutional Engine v5.0.1",
            neutral_insight: "Awaiting institutional confluence.",
            bull_insight: "Conditions favor risk assets. Momentum confirming expansion.",
            bear_insight: "Defensive posture advised. Elevated structural stress detected."
        },
        labels: {
            signal: "SIGNAL:",
            benchmark_mode: "BENCHMARK MODE",
            about: "ABOUT PROJECT",
            legal: "LEGAL NOTICE",
            archive: "DAILY ARCHIVE",
            back_to_terminal: "BACK TO TERMINAL",
            vix: "VIX (Equity Vol)",
            move: "MOVE (Bond Vol)",
            hy_spread: "HY Spread (OAS)",
            nfci: "NFCI (Financial Cond.)",
            yield_spread: "10Y-2Y Yield Spread",
            copper_gold: "Copper/Gold Ratio",
            dxy: "US Dollar Index",
            tnx: "US 10Y Yield",
            spy: "S&P 500 (SPY)"
        },
        subpages: {
            about: {
                title: "ABOUT OMNIMETRIC",
                mission: "Our Mission",
                mission_content: "OmniMetric is a personal quant-macro project dedicated to market transparency. We aggregate disparate institutional lead indicators—from high-yield spreads to bond volatility—into a single, high-density terminal interface. Our goal is to democratize institutional-grade macro analysis for individual researchers.",
                tech: "Quant Methodology",
                tech_content: "The GMS (Global Macro Signal) score is calculated using weighted algorithmic analysis of credit spreads, volatility indices, and growth proxies. Data is sourced from FRED (St. Louis Fed) and Yahoo Finance, processed through proprietary regime-detection logic.",
                footer_note: "OmniMetric is a 100% autonomous algorithmic project. We do not provide individual support or investment consulting."
            },
            legal: {
                title: "LEGAL NOTICE & COMPLIANCE",
                disclaimer: "Financial Disclaimer",
                disclaimer_content: "OmniMetric is an information aggregator. The information provided does not constitute investment, financial, or legal advice. All data and analysis are provided 'as is' without warranty of any kind.",
                usage: "Terms of Usage",
                usage_content: "Unauthorized automated scraping, data mining, or usage for AI training is strictly prohibited. Commercial usage requires a specific license. By using this terminal, you agree to these project-specific legal terms."
            },
            archive: {
                title: "DAILY HISTORICAL ARCHIVE",
                desc: "Select a date to view the terminal's historical macro regime and indicator state."
            }
        }
    },
    JP: {
        titles: {
            risk_score: "市場局面分析 (Market Regime)",
            insights: "定量的マクロインサイト",
            risk_factors: "機関投資家向けデータグリッド",
            legal: "法的通知・免責事項",
            delayed: "1時間遅延",
            partner_ad: "広告掲載枠",
            market_regime: "市場局面分析",
            risk_preference: "リスク選好",
            institutional_analysis: "機関投資家AI分析",
            sponsored: "スポンサー",
            current_strategy: "STRATEGIC BIAS",
            upcoming_events: "今後のリスクイベント",
            gms_score: "GMSスコア",
            breaking_news: "速報（BREAKING）",
            delayed_tick: "*15分遅延",
            methodology: "算出ロジック (METHODOLOGY)"
        },
        methodology: {
            title: "GMS QUANT METHODOLOGY",
            desc: "GMSスコアは、市場の「恐怖」「信用」「勢い」を統合し、0〜100で数値化した独自の定量的リスク指標です。",
            zone_accumulate: "60-100: ACCUMULATE (リスク選好)",
            zone_accumulate_desc: "株式・コモディティ・ハイイールド債への資金流入が推奨される拡大局面。",
            zone_neutral: "40-60: NEUTRAL (中立)",
            zone_neutral_desc: "トレンドレス。ボラティリティ収縮待ち。ポジション調整局面。",
            zone_defensive: "0-40: DEFENSIVE (リスク回避)",
            zone_defensive_desc: "現金・国債優位。パニック売りや信用収縮への警戒が必要。",
            inputs: "Inputs: VIX, MOVE, HY OAS, NFCI, SPY Momentum",
            scale_labels: {
                panic: "Panic (0)",
                neutral: "Neutral (50)",
                greed: "Greed (100)"
            }
        },
        strategy: {
            accumulate: "ACCUMULATE (強気)",
            neutral: "NEUTRAL (静観)",
            defensive: "DEFENSIVE (守備)"
        },
        events: {
            cpi: "CPI 消費者物価指数",
            fomc: "FOMC 政策金利発表",
            nfp: "米国雇用統計",
            high: "重要 (HIGH IMPACT)",
            critical: "最重要 (CRITICAL)",
            tue: "火",
            wed: "水",
            fri: "金",
            est: "EST" // Timezone usually kept en
        },
        attribution: {
            src: "ソース: FRED/CBOE • 更新: ライブ"
        },
        terms: {
            VIX: {
                def: "恐怖指数。S&P500の予想変動率。",
                benchmark: "基準: 20超は警戒域。30超はパニック売りを示唆。"
            },
            MOVE: {
                def: "米国債ボラティリティ指数。債券版VIX。",
                benchmark: "基準: 120超は債券市場の機能不全リスクを示唆。"
            },
            NFCI: {
                def: "シカゴ連銀金融環境指数。",
                benchmark: "基準: プラスは引き締め(弱気)、マイナスは緩和(強気)を示す。"
            },
            HY_SPREAD: {
                def: "ハイイールド債スプレッド (OAS)。企業の信用リスク。",
                benchmark: "基準: 5.0%超は信用収縮(クレジットクランチ)の兆候。"
            },
            COPPER_GOLD: {
                def: "銅金レシオ。世界経済の成長期待に対する代替指標。",
                benchmark: "基準: 上昇は景気拡大期待(リスクオン)を反映。"
            },
            BREADTH: {
                def: "市場の裾野 (RSP対SPY)。",
                benchmark: "基準: 均等加重指数が優位な場合、上昇相場は健全。"
            },
            SPY: {
                def: "S&P 500 ETF。米国株のエクスポージャー。",
                benchmark: "基準: 長期トレンドの維持が重要。"
            },
            TNX: {
                def: "米国10年債利回り。",
                benchmark: "基準: 4.5%を超えると株式バリュエーションを圧迫。"
            },
            DXY: {
                def: "ドルインデックス。",
                benchmark: "基準: 105超は世界的な流動性逼迫を招く。"
            },
            YIELD_SPREAD: {
                def: "長短金利差 (10年-2年)。",
                benchmark: "基準: 逆イールド(マイナス)はリセッションの先行指標。"
            }
        },
        legal_text: {
            t1: "オムニ・メトリック (究極のアセットハブ) は情報提供のみを目的としており、投資助言ではありません。本サイトの分析は独自のアルゴリズムによって生成されたものであり、無断でのAI学習、データマイニング、および商用目的の自動スクレイピングは固く禁じられています。本サイトへのアクセスをもって、これらの条件に同意したものとみなされます。",
            t2: "過去の実績は将来の成果を保証するものではありません。市場データは遅延する場合があります。",
            copyright: "Powered by オムニ・メトリック・プロジェクト 2026"
        },
        regime: {
            bull: "リスク選好",
            neutral: "中立局面",
            bear: "リスク回避",
            legend: "強気 > 60 // 弱気 < 40"
        },
        sections: {
            s1: "第Iセクション: 市場ボラティリティと警戒感",
            s2: "第IIセクション: 構造的信用リスクと予測",
            s3: "第IIIセクション: 主要リファレンス指標"
        },
        chart: {
            trend: "過去30日間のターミナルトレンド",
            sync: "シグナル同期待機中...",
            insight: "独占的インサイト",
            engine: "機関投資家向けエンジン v5.0.1",
            neutral_insight: "機関投資家の合意形成を待機中。",
            bull_insight: "リスク資産に追い風。モメンタムは拡張を継続。",
            bear_insight: "防衛的ポジションを推奨。構造的ストレスを検出。"
        },
        labels: {
            signal: "シグナル:",
            benchmark_mode: "ベンチマークモード",
            about: "ABOUT PROJECT",
            legal: "LEGAL NOTICE",
            archive: "DAILY ARCHIVE",
            back_to_terminal: "ターミナルに戻る",
            vix: "VIX (株式ボラティリティ)",
            move: "MOVE (債券ボラティリティ)",
            hy_spread: "HYスプレッド (実質利回り差)",
            nfci: "NFCI (金融環境指数)",
            yield_spread: "長短金利差 (10Y-2Y)",
            copper_gold: "銅金比率",
            dxy: "ドルインデックス",
            tnx: "米国10年債利回り",
            spy: "S&P 500 (米国株)"
        },
        subpages: {
            about: {
                title: "ABOUT OMNIMETRIC",
                mission: "プロジェクトの使命",
                mission_content: "OmniMetric（オムニ・メトリック）は、市場の透明性を追求する個人主導のクオンツ・マクロ・プロジェクトです。ハイイールド債のスプレッドから債券ボラティリティに至るまで、分散した機関投資家向け先行指標を1つの高密度なターミナル・インターフェースに統合します。私たちの目標は、機関投資家レベルのマクロ分析を個人の研究者が利用できるようにすることです。",
                tech: "クオンツ・メソドロジー",
                tech_content: "GMS（グローバル・マクロ・シグナル）スコアは、信用スプレッド、ボラティリティ指数、成長プロキシを加重アルゴリズムで分析して算出されます。データはFRED（セントルイス連銀）およびYahoo Financeから取得され、独自の局面検出ロジックによって処理されます。",
                footer_note: "OmniMetricは100％自律的なアルゴリズムプロジェクトです。個別のサポートや投資コンサルティングは行っておりません。"
            },
            legal: {
                title: "法的通知およびコンプライアンス",
                disclaimer: "免責事項",
                disclaimer_content: "OmniMetricは情報の集約プラットフォームです。提供される情報は投資、金融、または法的助言を構成するものではありません。すべてのデータと分析は、いかなる種類の保証もなく「現状のまま」提供されます。",
                usage: "利用規約",
                usage_content: "無断の自動スクレイピング、データマイニング、またはAI学習への利用は固く禁じられています。商用利用には特定のライセンスが必要です。本ターミナルを利用することで、これらのプロジェクト固有の法的条件に同意したものとみなされます。"
            },
            archive: {
                title: "デイリー・ヒストリカル・アーカイブ",
                desc: "過去の日付を選択して、当時のマクロ局面と指標の状態を確認できます。"
            }
        }
    },
    CN: {
        titles: {
            risk_score: "市场机制指标 (Market Regime)",
            insights: "量化宏观分析",
            risk_factors: "机构数据网格",
            legal: "法律声明",
            delayed: "延迟 1 小时",
            partner_ad: "机构合作伙伴广告位",
            market_regime: "市场机制",
            risk_preference: "风险偏好",
            institutional_analysis: "机构AI分析",
            sponsored: "赞助商",
            current_strategy: "当前策略",
            upcoming_events: "即将发生的风险事件",
            gms_score: "GMS评分",
            breaking_news: "突发新闻",
            delayed_tick: "*延迟15分",
            methodology: "方法论"
        },
        methodology: {
            title: "GMS QUANT METHODOLOGY",
            desc: "GMS评分将市场的“恐惧”、“信贷压力”和“动量”整合为一个0-100的专有量化风险指数。",
            zone_accumulate: "60-100: ACCUMULATE (风险偏好)",
            zone_accumulate_desc: "扩张阶段。建议资金流入股票、大宗商品和高收益债券。",
            zone_neutral: "40-60: NEUTRAL (中立)",
            zone_neutral_desc: "无趋势。等待波动率收缩。仓位调整阶段。",
            zone_defensive: "0-40: DEFENSIVE (风险回避)",
            zone_defensive_desc: "现金/国债主导。警惕恐慌性抛售和信贷收缩。",
            inputs: "Inputs: VIX, MOVE, HY OAS, NFCI, SPY Momentum",
            scale_labels: {
                panic: "Panic (0)",
                neutral: "Neutral (50)",
                greed: "Greed (100)"
            }
        },
        strategy: {
            accumulate: "积极累积",
            neutral: "中立观望",
            defensive: "防御姿态"
        },
        events: {
            cpi: "CPI 通胀数据",
            fomc: "FOMC 利率决议",
            nfp: "非农就业数据",
            high: "高影响",
            critical: "关键",
            tue: "周二",
            wed: "周三",
            fri: "周五",
            est: "EST"
        },
        attribution: {
            src: "来源: FRED/CBOE • 更新: 实时"
        },
        terms: {
            VIX: { def: "波动率指数。", benchmark: "基准：>20 为警戒区。" },
            MOVE: { def: "债券市场波动率。", benchmark: "基准：>120 表明系统性压力。" },
            NFCI: { def: "国家金融状况指数。", benchmark: "基准：正值为紧缩，负值为宽松。" },
            HY_SPREAD: { def: "高收益债券利差。", benchmark: "基准：>5% 表明信贷压力。" },
            COPPER_GOLD: { def: "铜金比率。", benchmark: "基准：上升表明经济扩张。" },
            BREADTH: { def: "市场广度。", benchmark: "基准：广泛的参与表明牛市健康。" },
            SPY: { def: "标准普尔 500 ETF。", benchmark: "基准：趋势向上为风险开启。" },
            TNX: { def: "10年期国债收益率。", benchmark: "基准：>4.5% 压低估值。" },
            DXY: { def: "美元指数。", benchmark: "基准：>105 导致流动性紧缩。" },
            YIELD_SPREAD: { def: "收益率曲线。", benchmark: "基准：倒挂为衰退信号。" }
        },
        legal_text: {
            t1: "OmniMetric (终极资产中心) 仅供参考，不构成投资建议。本文信息由专有算法生成。未经书面许可，严禁将本网站数据用于 AI 训练、数据挖掘或商业自动抓取。访问本网站即表示您同意这些条款。",
            t2: "过往表现不代表未来结果。市场数据按原样提供。",
            copyright: "Powered by OmniMetric Project 2026"
        },
        regime: {
            bull: "风险偏好",
            neutral: "中立机制",
            bear: "风险规避",
            legend: "看涨 > 60 // 看跌 < 40"
        },
        sections: {
            s1: "第一部分：市场波动与恐惧",
            s2: "第二部分：结构性信贷与预测",
            s3: "第三部分：参考基准"
        },
        chart: {
            trend: "30天终端趋势",
            sync: "正在等待信号同步...",
            insight: "独家见解",
            engine: "机构版版本 v5.0.1",
            neutral_insight: "等待机构达成共识。",
            bull_insight: "条件有利于风险资产。动量确认扩张。",
            bear_insight: "建议采取防御性姿态。检测到结构性压力。"
        },
        labels: {
            signal: "信号:",
            benchmark_mode: "基准模式",
            about: "ABOUT PROJECT",
            legal: "LEGAL NOTICE",
            archive: "DAILY ARCHIVE",
            back_to_terminal: "返回终端",
            vix: "VIX (股票波动率)",
            move: "MOVE (债券波动率)",
            hy_spread: "HY利差 (OAS)",
            nfci: "NFCI (金融状况指数)",
            yield_spread: "10Y-2Y收益率差",
            copper_gold: "铜金比率",
            dxy: "美元指数",
            tnx: "美国10年期收益率",
            spy: "标普500 (SPY)"
        },
        subpages: {
            about: {
                title: "关于 OMNIMETRIC",
                mission: "项目使命",
                mission_content: "OmniMetric 是一个致力于提高市场透明度的个人量化宏观项目。我们将分散的机构领先指标（从高收益债利差到债券波动率）汇总到一个高密度的终端界面中。我们的目标是为个人研究人员提供机构级的宏观分析工具。",
                tech: "量化方法",
                tech_content: "GMS（全球宏观信号）评分是通过对信用利差、波动率指数和增长指标进行加权算法分析得出的。数据源自 FRED（圣路易斯联储）和雅虎财经，并通过专有的机制检测逻辑进行处理。",
                footer_note: "OmniMetric 是一个100%自律的算法项目。我们不提供个人支持或投资咨询。"
            },
            legal: {
                title: "法律声明与合规性",
                disclaimer: "免责声明",
                disclaimer_content: "OmniMetric 是一个信息汇总平台。所提供的信息不构成投资、金融或法律建议。所有数据和分析均按“原样”提供，不作任何形式的保证。",
                usage: "使用条款",
                usage_content: "严禁未经授权的自动抓取、数据挖掘或用于 AI 训练。商业用途需要特定许可。使用本终端即表示您同意这些特定的法律条款。"
            },
            archive: {
                title: "每日历史存档",
                desc: "选择日期以查看终端的历史宏观机制和指标状态。"
            }
        }
    },
    ES: {
        titles: {
            risk_score: "Indicador de Régimen de Mercado",
            insights: "Análisis Macro Cuantitativo",
            risk_factors: "Red de Datos Institucionales",
            legal: "AVISO LEGAL",
            delayed: "Retraso de 1H",
            partner_ad: "Espacio Publicitario Institucional",
            market_regime: "RÉGIMEN DE MERCADO",
            risk_preference: "PREFERENCIA DE RIESGO",
            institutional_analysis: "Análisis AI Institucional",
            sponsored: "PATROCINADO",
            current_strategy: "ESTRATEGIA ACTUAL",
            upcoming_events: "PRÓXIMOS EVENTOS DE RIESGO",
            gms_score: "PUNTUACIÓN GMS",
            breaking_news: "NOTICIAS DE ÚLTIMA HORA",
            delayed_tick: "*RETRASO 15m",
            methodology: "METODOLOGÍA"
        },
        methodology: {
            title: "METODOLOGÍA CUANTITATIVA GMS",
            desc: "El puntaje GMS integra el 'Miedo', 'Estrés Crediticio' y 'Momento' del mercado en un índice de riesgo cuantitativo propietario de 0-100.",
            zone_accumulate: "60-100: ACUMULAR (Risk On)",
            zone_accumulate_desc: "Fase de expansión. Se sugieren entradas en Acciones, Materias Primas y Bonos de Alto Rendimiento.",
            zone_neutral: "40-60: NEUTRAL (Sin Tendencia)",
            zone_neutral_desc: "Compresión de volatilidad. Fase de ajuste de posición.",
            zone_defensive: "0-40: DEFENSIVA (Risk Off)",
            zone_defensive_desc: "Dominio de efectivo/bonos. Cuidado con la venta de pánico y la contracción del crédito.",
            inputs: "Inputs: VIX, MOVE, HY OAS, NFCI, SPY Momentum",
            scale_labels: {
                panic: "Panic (0)",
                neutral: "Neutral (50)",
                greed: "Greed (100)"
            }
        },
        strategy: {
            accumulate: "ACUMULAR",
            neutral: "NEUTRAL",
            defensive: "DEFENSIVA"
        },
        events: {
            cpi: "DATOS DE INFLACIÓN (CPI)",
            fomc: "DECISIÓN DE TASAS FOMC",
            nfp: "NÓMINAS NO AGRÍCOLAS",
            high: "ALTO IMPACTO",
            critical: "CRÍTICO",
            tue: "MAR",
            wed: "MIÉ",
            fri: "VIE",
            est: "EST"
        },
        attribution: {
            src: "FUENTE: FRED/CBOE • ACTUALIZ.: VIVO"
        },
        terms: {
            VIX: { def: "Índice de Volatilidad.", benchmark: "Ref: >20 Precaución." },
            MOVE: { def: "Volatilidad de Bonos.", benchmark: "Ref: >120 Estrés sistémico." },
            NFCI: { def: "Índice de Condiciones Financieras.", benchmark: "Ref: Positivo = Ajustado." },
            HY_SPREAD: { def: "Diferencial High Yield.", benchmark: "Ref: >5% Estrés crediticio." },
            COPPER_GOLD: { def: "Ratio Cobre/Oro.", benchmark: "Ref: Subida = Expansión." },
            BREADTH: { def: "Amplitud del Mercado.", benchmark: "Ref: Participación amplia es saludable." },
            SPY: { def: "S&P 500 ETF.", benchmark: "Ref: Alcista = Risk On." },
            TNX: { def: "Rendimiento 10 Años.", benchmark: "Ref: >4.5% presiona valoraciones." },
            DXY: { def: "Índice Dólar.", benchmark: "Ref: >105 ajusta liquidez." },
            YIELD_SPREAD: { def: "Curva de Tipos.", benchmark: "Ref: Inversión = Recesión." }
        },
        legal_text: {
            t1: "OmniMetric ('The Ultimate Asset Hub') proporciona análisis macro cuantitativos solo con fines informativos. No constituye asesoramiento de inversión. Se prohíbe estrictamente el raspado (scraping) automatizado y el entrenamiento de IA sin licencia comercial. Al acceder a este sitio, acepta estos términos.",
            t2: "El rendimiento pasado no garantiza resultados futuros.",
            copyright: "Powered by OmniMetric Project 2026"
        },
        regime: {
            bull: "Preferencia al Riesgo",
            neutral: "Régimen Neutral",
            bear: "Aversión al Riesgo",
            legend: "ALCISTA > 60 // BAJISTA < 40"
        },
        sections: {
            s1: "SECCIÓN I: VOLATILIDAD Y TEMOR",
            s2: "SECCIÓN II: CRÉDITO Y PRONÓSTICOS",
            s3: "SECCIÓN III: PUNTOS DE REFERENCIA"
        },
        chart: {
            trend: "Tendencia de Terminal de 30 Días",
            sync: "Esperando sincronización de señal...",
            insight: "Información Propietaria",
            engine: "Motor Institucional v5.0.1",
            neutral_insight: "Esperando confluencia institucional.",
            bull_insight: "Las condiciones favorecen los activos de riesgo.",
            bear_insight: "Se recomienda una postura defensiva."
        },
        labels: {
            signal: "SEÑAL:",
            benchmark_mode: "MODO DE REFERENCIA",
            about: "ABOUT PROJECT",
            legal: "LEGAL NOTICE",
            archive: "DAILY ARCHIVE",
            back_to_terminal: "VOLVER AL TERMINAL",
            vix: "VIX (Vol. Variable)",
            move: "MOVE (Vol. Bonos)",
            hy_spread: "HY Spread (OAS)",
            nfci: "NFCI (Cond. Financieras)",
            yield_spread: "Spread 10Y-2Y",
            copper_gold: "Ratio Cobre/Oro",
            dxy: "Índice Dólar",
            tnx: "Rendimiento 10A",
            spy: "S&P 500 (SPY)"
        },
        subpages: {
            about: {
                title: "SOBRE OMNIMETRIC",
                mission: "Nuestra Misión",
                mission_content: "OmniMetric es un proyecto personal de macro-cuantitativo dedicado a la transparencia del mercado. Agregamos indicadores líderes institucionales dispersos en una única interfaz de terminal de alta densidad. Nuestro objetivo es democratizar el análisis macro profesional para investigadores individuales.",
                tech: "Metodología Cuantitativa",
                tech_content: "El puntaje GMS (Global Macro Signal) se calcula mediante un análisis algorítmico ponderado de diferenciales de crédito, índices de volatilidad y proxis de crecimiento.",
                footer_note: "OmniMetric es un proyecto algorítmico 100% autónomo. No proporcionamos soporte individual ni consultoría de inversión."
            },
            legal: {
                title: "AVISO LEGAL Y CUMPLIMIENTO",
                disclaimer: "Aviso Legal",
                disclaimer_content: "OmniMetric es un agregador de información. La información proporcionada no constituye asesoramiento de inversión. Todos los datos se proporcionan 'tal cual'.",
                usage: "Términos de Uso",
                usage_content: "Queda estrictamente prohibido el raspado automatizado y el entrenamiento de IA sin licencia comercial. Al usar esta terminal, acepta estos términos legales."
            },
            archive: {
                title: "ARCHIVO HISTÓRICO DIARIO",
                desc: "Seleccione una fecha para ver el régimen macro histórico y el estado de los indicadores de la terminal."
            }
        }
    }
};
